server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
         - id: flights-api
           uri: lb://flights-api
           predicates:
             - Path=/flights/**
             - Path=/companies/**
         - id: tickets-api
           uri: lb://tickets-api
           predicates:
             - Path=/tickets/**
management:
  endpoints:
    web:
      exposure:
        include: 
          - health
          - info








