server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: users-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - AuthFilter
        - id: flights-route
          uri: lb://FLIGHTS-API
          predicates:
            - Path=/flights/**
          filters:
            - AuthFilter
        - id: companies-route
          uri: lb://FLIGHTS-API
          predicates:
            - Path=/companies/**
          filters:
            - AuthFilter
        - id: tickets-route
          uri: lb://TICKETS-API
          predicates:
            - Path=/tickets/**
          filters:
            - AuthFilter

validate:
  token: ${VALIDATE_TOKEN_URL:http://auth-service/auth/validate-token?validateTokenReq=}














