server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      routes:
        - id: flights-api-route
          uri: lb://FLIGHTS-API
          predicates:
            - Path=/flights/**
        - id: companies-api-route
          uri: lb://FLIGHTS-API
          predicates:
            - Path=/companies/**
        - id: tickets-api-route
          uri: lb://TICKETS-API
          predicates:
            - Path=/tickets/**

management:
  endpoints:
    web:
      base-path: /admin
  endpoint:
    health:
      show-details: always
    info:
      enabled: true










