server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: flights-api
          uri: lb://flights-api
          predicates:
            - Path=/flights/**
            - Path=/companies/**
        - id: tickets-api
          uri: lb://tickets-api
          predicates:
            - Path=/tickets/**









