server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      routes:
        - id: flights-api
          uri: lb://FLIGHTS-API
          predicates:
            - Path=/flights/**
 #           - Path=/companies/**
  #      - id: tickets-api
   #       uri: lb://TICKETS-API
    #      predicates:
     #       - Path=/tickets/**









