spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/irinaponzi/airlines-microservices
          search-paths: config-data
  application:
    name: config-service
server:
  port: 8081
