server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/irinaponzi/airlines-microservices.git
          search-paths: config-data
#          clone-on-start: true

  application:
    name: config-server
